#!/usr/bin/with-contenv bash

### Setup Persistent Storage
if [ ! -d /data ]; then
  mkdir -p /data
fi

chown -R clamav:clamav /data

### Setup Logs
mkdir -p /var/log/clamav
chown -R clamav:clamav /var/log/clamav

### Update Definitions
echo '** [freshclam] Updating Definitions ..'
freshclam --user=clamav --verbose --show-progress --config-file=/etc/clamav/freshclam.conf --log=/var/log/clamav/freshclam.log


mkdir -p /tmp/state
touch /tmp/state/10-clamd-init
